- id: doi:10.1016/j.xpro.2021.100908
  image: https://pbs.twimg.com/profile_images/1225089025129644032/TBdQps0G_400x400.jpg
  date: 2021-12-17
  tags:
    - single cell isolation
    - immunology
- id: doi:10.1016/j.cell.2021.05.013
  image: https://publons.com/media/thumbs/journal/logos/22de2414-0b91-4060-81c2-e0d80647d1cd.png.200x200_q95_detail_letterbox_upscale.png
  date: 2021-6-14
  tags:
    - scRNA seq
    - oral atlas
    - periodontitis
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2021.04.06.438702v1
    - type: source
      link: https://github.com/williamsdrake/oralAtlas
      text: Analysis source
    - type: source
      link: https://oral.cellatlas.io/
      text: Interactive data viewer
- id: doi:10.1126/science.aay5731
  image: https://www.digital-science.com/wp-content/uploads/2017/03/tumblr_inline_onemlhvtDL1qk1s0s_1280.png
  date: 2021-1-15
  tags:
    - AIRE-deficiency
    - interferonopathy
    - immunology
- id: doi:10.1038/s41586-020-2745-3
  image: https://upload.wikimedia.org/wikipedia/commons/d/db/Nature_journal_logo.svg
  date: 2020-9-23
  tags:
    - maternal microbiome
    - fetal neurodevelopment
    - metabolites
