- id: doi:10.1016/j.xpro.2021.100908
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166721006146-fx1_lrg.jpg
  date: 2021-12-17
  tags:
    - single cell
    - cell isolation
    - immunology
- id: doi:10.1016/j.cell.2021.05.013
  image: https://publons.com/media/thumbs/journal/logos/22de2414-0b91-4060-81c2-e0d80647d1cd.png.200x200_q95_detail_letterbox_upscale.png
  date: 2021-6-14
  tags:
    - single cell RNA sequencing
    - oral atlas
    - periodontitis
  extra-links:
    - type: preprint
      link: https://www.biorxiv.org/content/10.1101/2021.04.06.438702v1
    - type: source
      link: https://github.com/williamsdrake/oralAtlas
      text: Analysis source
    - type: source
      link: https://oral.cellatlas.io/
      text: Interactive data viewer
